## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If I have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
# import packages
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

10

In [5]:
# vector
vector = torch.tensor([18, 10])
vector

tensor([18, 10])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0][0]

tensor(7)

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [4 ,5, 6, 4],
                        [7, 8, 9, 4],
                        [0, 0, 0, 0]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4],
         [0, 0, 0, 0]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 4])

In [15]:
tensor4 = torch.randn(2, 5, 2)
tensor4

tensor([[[ 0.5288, -0.0320],
         [-0.5737, -0.5919],
         [ 0.4267, -0.9223],
         [-1.1306, -0.4964],
         [ 0.1495, -0.9519]],

        [[-0.4062, -0.5573],
         [-1.6255, -0.0399],
         [ 1.1167,  0.4200],
         [ 0.2962, -0.6541],
         [-0.9121,  0.8903]]])

In [16]:
tensor4.shape

torch.Size([2, 5, 2])

### Random Tensors

In [17]:
# random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8049, 0.0495, 0.4455, 0.4113],
        [0.4917, 0.7261, 0.1017, 0.2114],
        [0.3260, 0.8203, 0.3184, 0.4705]])

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
random_image_size_tensor

tensor([[[0.4930, 0.6398, 0.6561,  ..., 0.1043, 0.2684, 0.7050],
         [0.3791, 0.8546, 0.5306,  ..., 0.8136, 0.1386, 0.3841],
         [0.5511, 0.4716, 0.8209,  ..., 0.5695, 0.8518, 0.0884],
         ...,
         [0.3015, 0.0500, 0.8720,  ..., 0.3102, 0.8095, 0.7146],
         [0.0755, 0.3869, 0.5527,  ..., 0.4145, 0.9873, 0.1444],
         [0.0500, 0.8292, 0.0360,  ..., 0.1042, 0.4142, 0.4327]],

        [[0.4216, 0.3482, 0.9962,  ..., 0.9065, 0.3228, 0.1221],
         [0.2734, 0.8162, 0.3042,  ..., 0.7514, 0.1097, 0.4138],
         [0.2784, 0.5542, 0.7063,  ..., 0.3815, 0.3529, 0.3825],
         ...,
         [0.7033, 0.1600, 0.4988,  ..., 0.8184, 0.8872, 0.0106],
         [0.2156, 0.6008, 0.3673,  ..., 0.5543, 0.8908, 0.3635],
         [0.7372, 0.8822, 0.4620,  ..., 0.9990, 0.6494, 0.8819]],

        [[0.2511, 0.0061, 0.5529,  ..., 0.6359, 0.7330, 0.7849],
         [0.8050, 0.2668, 0.5906,  ..., 0.7741, 0.7315, 0.1610],
         [0.2584, 0.3445, 0.6366,  ..., 0.1785, 0.1185, 0.

### Zeros and ones

In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create a tensor of ones
ones = torch.ones(size = (10, 10, 10))
ones.ndim

3

### Create a range of tensors and tensors-like

In [25]:
# use torch.arange
one_to_hundred = torch.arange(start = 0, end = 101, step = 10)

In [26]:
# creating tensors like
ten_zeroes = torch.zeros_like(one_to_hundred)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [27]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = float_16_tensor.type(torch.int32)
int_32_tensor.dtype

torch.int32

In [32]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Manipulating Tensors (tensor operations)


Tensor operations include addition, subtraction, multiplication, division, and matrix multiplication.

In [33]:
# addition
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [34]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [35]:
# subtraction
tensor - 10

tensor([-9, -8, -7])

In [36]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

In [37]:
tensor_1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor_2 = torch.tensor([[4, 3],
                         [2, 1]])
tensor_1, tensor_2, torch.matmul(tensor_1, tensor_2)

(tensor([[1, 2],
         [3, 4]]),
 tensor([[4, 3],
         [2, 1]]),
 tensor([[ 8,  5],
         [20, 13]]))

### One of the most common errors in deep learning is shape errors

In [38]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

To fix out tensor shape issues, we can manipulate the shape of one of our tensors

In [39]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [40]:
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min, max, mean, sum etc (tensor aggregation)

In [41]:
# create a tensor
x = torch.arange(0, 20, 2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
x.min()

tensor(0)

In [43]:
x.max()

tensor(18)

In [44]:
x.sum()

tensor(90)

In [45]:
x.type(torch.float).mean()

tensor(9.)

In [46]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [47]:
## reshaping, stacking, squeezing and unsqueezing tensors

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [54]:
# stack tensors on top
x_stacked = torch.stack([x, x, x, x], dim = 0)
x, x_stacked

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [61]:
# squeeze
x = torch.zeros(2, 1, 2, 1, 2)
y = torch.squeeze(x)
x, y

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [66]:
# unsqueeze
x = torch.tensor([1, 2, 3, 4])
x, x.shape, x.ndim

(tensor([1, 2, 3, 4]), torch.Size([4]), 1)

In [80]:
y = torch.unsqueeze(x, -2)
y, y.shape

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [86]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x = torch.randn(2,3,4)
x

tensor([[[-0.5080,  1.3640, -1.6455, -0.8517],
         [ 2.2846,  0.0837,  0.0585,  0.0923],
         [-0.7341,  0.3815, -0.0363, -1.1176]],

        [[-2.2717, -0.1485,  0.5943, -0.1263],
         [-0.6161,  0.5596, -2.4099, -0.0666],
         [ 0.7643, -1.8461, -0.6696,  1.8911]]])

In [88]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([4, 2, 3])

## Indexing (selecting data from tensors)

In [98]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [101]:
# index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [102]:
x[0][0]

tensor([1, 2, 3])

In [106]:
x[0][2][2]

tensor(9)

In [107]:
x[:, 0]

tensor([[1, 2, 3]])

In [109]:
# get all values of the 0th dimension and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [110]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [111]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [115]:
# return 9
x[0][2][2]

tensor(9)

In [118]:
# return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

In [119]:
# numpy array to tensor
import torch
import numpy as np

## Reproducibility (tring to take random out of random)

In [2]:
import torch

# this is done by setting the random.seed and I know how to do this so we are gooing to skip this one

## GPU usage in PyTorch

In [4]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count number of devices
torch.cuda.device_count()

1

In [6]:
## putting tensors and models on the GPU

# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

print(tensor.device)

cpu


In [7]:
# move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

## Exercises and extra curriculum

In [15]:
# set random seed to 0
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

In [16]:
# create a random tensor with shape `(7, 7)`
x = torch.rand(7, 7)
x.shape

torch.Size([7, 7])

In [17]:
# matrix mulitplcation of x with another tensor of shape 1, 7
# okay so this is a trick question, cause to matrix multiply tenors, their inner dimensions has to be the same
# let's transpose the second tensor

y = x @ torch.rand(1, 7).T
y

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [20]:
# SEED for GPU using cude
torch.cuda.manual_seed(1234)

In [21]:
# set random seed to 1234
RANDOM_SEED=1234
torch.manual_seed(seed=RANDOM_SEED)

In [24]:
# create two random tensors of shape (2, 3)
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
tensor_A.device, tensor_B.device

(device(type='cpu'), device(type='cpu'))

In [25]:
# send both to gpu
tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)
tensor_A_gpu.device, tensor_B_gpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [27]:
# mulitple tensor_A and tensor_B
tensor_AB = tensor_A @ tensor_B.T
tensor_AB

tensor([[1.2478, 1.0013],
        [0.6995, 0.6665]])

In [29]:
# max value of tensor_AB
tensor_AB.max()

tensor(1.2478)

In [30]:
# min value of tensor_AB
tensor_AB.min()

tensor(0.6665)

In [31]:
# index of max value of tensor_AB
tensor_AB.argmax()

tensor(0)

In [33]:
# index of min value of tensor_AB
tensor_AB.argmin()

tensor(3)

In [37]:
# make a random tensor with shape 1, 1, 1, 10
random_tensor = torch.rand(1, 1, 1, 10)
random_tensor, random_tensor.shape

(tensor([[[[0.4189, 0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658,
            0.9149, 0.3993]]]]),
 torch.Size([1, 1, 1, 10]))

In [38]:
squeezed = random_tensor.squeeze()
squeezed, squeezed.shape

(tensor([0.4189, 0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149,
         0.3993]),
 torch.Size([10]))